### ISSUE TITLE
combine auth and connect?

### ISSUE THREAD

**Issue by pfrazee** [ssbc/ssb-client#10]
What would you think of putting the .auth call into .connect, and having the auth object be passed into .connect? So:

``` js
var client = SSBClient({ host: 'localhost' })
client.connect(abortIf)
client.auth(SSBKeys.createAuth(keys), abortIf)
```

becomes

``` js
var client = SSBClient({ host: 'localhost' })
client.connect(SSBKeys.createAuth(keys), abortIf)
```

**Comment by dominictarr** [comment]
yeah my plan is to build authorization into the connection security

**Comment by dominictarr** [comment]
yeah, so it will basically end up like you describe.

**Comment by pfraze** [comment]
ok, going to make a PR doing this
