### ISSUE TITLE
WebSocket closes after idling

### ISSUE THREAD

**Issue by pfrazee** [ssbc/ssb-client#13]
I have an app connecting on my local computer which will do some work on sbot, then idle until the user does something. After 30s, the websocket connection closes.

I checked the logs, and it doesn't look like the close is initiated by sbot or the app. I think this is a choice by the browser (or possibly server code) to disconnect. TCP keepalive isn't used in Websockets, you have to send ping/pong messages to keep it active.

The app could listen for closes and reconnect. This line before any activity also works:

``` js
if (client.closed)
    client.reconnect().auth(SSBKeys.createAuth(user.keys))
```

But I don't like having to do that in every application. It also closes any live streams, so they have to be re-initialized.

This does work as a keepalive:

``` js
setInterval(function () {
  console.log('ping')
  ssb.whoami()
}, 15e3)
```

Do we want to consider a `ping` method in the ssb api? What's the best way to deal with this?

**Comment by dominictarr** [comment]
yeah I think ping because having a presense api would be useful for other things too... like realtime chat

**Comment by pfraze** [comment]
Hmm, why isn't this happening in phoenix?
