### ISSUE TITLE
setting manual config options seems to be broken

### ISSUE THREAD

**Issue by mmckegg** [ssbc/ssb-client#18]
`ssbClient(keys, 'appname')` works fine, however if you are wanting to pass your own config in (e.g. `ssbClient(keys, ssbConfig('appname', { port: 12345 }))`), everything breaks.

It seems there is something fishy going on [here](https://github.com/ssbc/ssb-client/blob/7d728d80bb3a7d1bbd873622563897459e6055fb/index.js#L46). 

`config` is set to `{}` and the options are basically thrown away.

**Comment by mmckegg** [comment]
@dominictarr and yes the rumours are true! I'm building something on top of ssb 😄

**Comment by dominictarr** [comment]
should be fixed in 86d0b95326caac6ad1b7fac2ae2a78f07ff53a60

also, now self hosted at ssb://%84icn///K51s+OvwQY1qdx7Y7UhdyO6LX7+xqpkXcNA=.sha256

**Comment by dominictarr** [comment]
in 4.1.0

**Comment by dominictarr** [comment]
And yes! very excited to see what you come up with!

**Comment by regular** [comment]
@mmckegg do you still have this issue? I think its fixed in scuttlebot@13
