### ISSUE TITLE
separate crypto code?

### ISSUE THREAD

**Issue by dominictarr** [ssbc/ssb-client#2]
I'm thinking that maybe we shouldn't mix crypto code with networking code.
If you pass you keys to it it needs to be audited, we want to minimize that. maybe it's better to make this just be about getting an rpc connection and then having another part to manage creating the messages.

Also, I noticed that this `publish` implementation will not work if you call it in parallel,
but the implementation in https://github.com/ssbc/secure-scuttlebutt/blob/master/feed.js 
does queue it so you can call `feed.add` as many times as you like.

**Comment by pfraze** [comment]
looking at https://github.com/ssbc/secure-scuttlebutt/blob/master/feed.js, I think we could actually use `feed` with an rpc connection to ssb. Maybe we remove `publish` and add a `createFeed` function to ssb-client which takes the keys? We'd still need to solve auth, though.

**Comment by pfraze** [comment]
does the rpc connection to scuttlebot actually need to prove key ownership? if we just let connections from localhost default to the 'local' role, we wouldnt need any auth crypto either

**Comment by pfraze** [comment]
actually, I think we will want the rpc connection to authenticate the keypair in the future, even if we dont use it now

**Comment by dominictarr** [comment]
@pfraze yeah that is a good point! in that case, we do not need to pass ssb-client your keys, until you post a message.

**Comment by pfraze** [comment]
ok so if we want to pull all the crypto out, the api would look like...

```js

var Client = require('./')

var config  = require('ssb-config')
var ssbKeys = require('ssb-keys')
var keys = ssbKeys.loadOrCreateSync(config)

function abortIf (err) {
  if(err) throw err
}

var client = Client(config)
  .connect(abortIf)
  .auth(ssbKeys.signObj(keys, {
    role: 'client',
    ts: Date.now(),
    public: keys.public
  }, abortIf)

var feed = client.createFeed(keys)
feed.add({
  type: 'post', text: 'hello, world!'
}, function (err, msg) {
  abortIf(err)
  console.log(msg)
  client.close()
})

```

**Comment by pfraze** [comment]
The auth step is a bunch of boilerplate -- can we get away with just passing the keys to `auth` and putting the auth-object-creation in there?

```js
var client = Client(config)
  .connect(abortIf)
  .auth(keys, abortIf)
```

**Comment by dominictarr** [comment]
yes, but we can put that auth bit in a module: `.auth(ssbKeys.createAuth(keys), cb)`

**Comment by pfraze** [comment]
ok, I'm cool with that. let's do it

**Comment by pfraze** [comment]
done with https://github.com/ssbc/ssb-client/pull/5

**Comment by dominictarr** [comment]
reopening this because keys are still passed in for `createFeed`
