### ISSUE TITLE
no sbot.on('close') event?

### ISSUE THREAD

**Issue by ansuz** [ssbc/ssb-client#20]
I see an `sbot.closed` flag, and there's a `sbot.on` which adds to `sbot._events`, but it doesn't seem as though anything gets fired when closed changes from `false` -> `true`.

I can work around this with a setInterval, but if this functionality exists I'd rather use it. Am I missing something?

**Comment by dominictarr** [comment]
the event is `"closed"`

**Comment by ansuz** [comment]
yup, that does it, thanks!
