### ISSUE TITLE
TypeError: cb is not a function

### ISSUE THREAD

**Issue by evbogue** [ssbc/ssb-client#22]
I've started getting this error in minbase since upgrading to `ssb-client@4.5.0`. It seems to track back to the blobs logic in `ssb-client`.  Downgrading to the previous version appears to solve the issue.

The error:
```
cb is not a function
TypeError: cb is not a function`
    at file:///home/ev/minbase/build/index.html:14211:11
    at file:///home/ev/minbase/build/index.html:9766:14
    at file:///home/ev/minbase/build/index.html:9715:14
    at file:///home/ev/minbase/build/index.html:9707:5
    at file:///home/ev/minbase/build/index.html:9756:17
    at file:///home/ev/minbase/build/index.html:11229:24
    at file:///home/ev/minbase/build/index.html:11451:7
    at next (file:///home/ev/minbase/build/index.html:11225:11)
    at sink (file:///home/ev/minbase/build/index.html:11246:9)
    at sink (file:///home/ev/minbase/build/index.html:9758:7)
```

Which leads to the `cb(err, actualHash)` in `blobs.js`

Not sure how to fix? cc @regular

**Comment by mmckegg** [comment]
Yeah, getting this in patchcore too, every time a blob is added. Everything still seems to work though.

https://github.com/ssbc/patchwork/issues/580

Here's a stack trace with filenames:

```
TypeError: cb is not a function
    at /Users/matt/Code/patchwork/node_modules/ssb-client/blobs.js:29:11
    at /Users/matt/Code/patchwork/node_modules/muxrpc/pull-weird.js:69:14
    at /Users/matt/Code/patchwork/node_modules/muxrpc/pull-weird.js:18:14
    at /Users/matt/Code/patchwork/node_modules/muxrpc/pull-weird.js:10:5
    at /Users/matt/Code/patchwork/node_modules/muxrpc/pull-weird.js:59:17
    at /Users/matt/Code/patchwork/node_modules/pull-stream/sinks/drain.js:20:24
    at /Users/matt/Code/patchwork/node_modules/pull-stream/sources/values.js:19:7
    at next (/Users/matt/Code/patchwork/node_modules/pull-stream/sinks/drain.js:16:11)
    at sink (/Users/matt/Code/patchwork/node_modules/pull-stream/sinks/drain.js:37:9)
    at sink (/Users/matt/Code/patchwork/node_modules/muxrpc/pull-weird.js:61:7)
```

cc @dominictarr

**Comment by regular** [comment]
hm .. I'll have a look!

**Comment by regular** [comment]
@evbogue you don't provide a callback to blobs.add() in modules/sbot.js line 111. You can now remove that ugly hack to find out if blob.add was successful and you don't need to hash the data yourself anymore.

Instead of:
```
     sbot_blobs_add: rec.sink(function (cb) {
        return pull(
          Hash(function (err, id) {
            if(err) return cb(err)
            //completely UGLY hack to tell when the blob has been sucessfully written...
            var start = Date.now(), n = 5
            ;(function next () {
              setTimeout(function () {
                sbot.blobs.has(id, function (err, has) {
                  if(has) return cb(null, id)
                  if(n--) next()
                  else cb(new Error('write failed'))
                })
              }, Date.now() - start)
            })()
          }),
          sbot.blobs.add()
        )
      }),
```

just

```
     sbot_blobs_add: sbot.blobs.add
```

I think

**Comment by regular** [comment]
`blobs.add` now behaves like documented here: http://scuttlebot.io/apis/scuttlebot/blobs.html
The callback is called with `err` and `hash`. So, typically you'd call `blobs.add` with just the callback and then receive the has for the blob in the callback.

**Comment by dominictarr** [comment]
ah yes, the "ugly hack" is now part of ssb-client ;) !

**Comment by regular** [comment]
@dominictarr [I've got hurt feelings](https://www.youtube.com/watch?v=EuJzSTNDUGI) :p (kidding)

**Comment by evbogue** [comment]
Thanks for your help @regular! Fixed in `%AViTlqvcrQPRwowXa8NH3OfKUvLe3vmBKKCO/BiH8mU=.sha256`

**Comment by regular** [comment]
@evbogue you are welcome, I'm glad it works!

**Comment by dominictarr** [comment]
@regular oh, I was refering to the comment (my hack in the code you posted, where I poll `has` to detect when the blob is up) but I just realized that is not actually the hack in ssb-client.

**Comment by regular** [comment]
@dominictarr All good! I realised after posting that this kind of joke is incompatible with written communication. No feelings were actually hurt, I was just jumping onto the opportunity to finally make a reference to Flight of the Conchords in the ssb context. If it wasn't for ssb, this show would be my sole source of information about NZ. :)
