### ISSUE TITLE
manifest.json in the browser

### ISSUE THREAD

**Issue by christianbundy** [ssbc/ssb-client#25]
I'm trying to run this in the browser, but it's failing when it can't find `manifest.json`. Is there a known workaround for this? I'm sure the `fs.readFileSync()` is being polyfilled, but I'm unsure how to actually generate `manifest.json`. Thanks!

**Comment by dominictarr** [comment]
hmm, I think the current technique is to load the manifest with require in the client so it's part of the same javascript bundle... how does minbay do it @evbogue ?

**Comment by evbogue** [comment]
@christianbundy @dominictarr Yes, require: https://github.com/evbogue/minbase/blob/5a3fa18936e330ed99ac6c0e1af071cc494091e1/modules/sbot.js#L69

The manifest itself is created manually, unlike in `scuttlebot` where it's generated if it doesn't already exist. https://github.com/evbogue/minbase/blob/master/manifest.json

Feel free to use the one from minbase if you want @christianbundy.
