### ISSUE TITLE
no sbot.private function

### ISSUE THREAD

**Issue by joelamouche** [ssbc/ssb-client#30]
Hi, 

When using sbot.private.publish(etc), with sbot being ssbClient(function (err, sbot) {blabla}) I get this error:

 (node:41004) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'publish' of undefined
(node:41004) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

And when loging sbot.private, I get undefined, and when loging sbot object I don't find the private function.

Am I missing something?

Thanks in advance

**Comment by arj03** [comment]
You probably need to install the ssb-private plugin.

**Comment by cryptix** [comment]
yup. sbot [recently removed the old private](https://github.com/ssbc/scuttlebot/commit/8d0f5039e1f7370a1e27b0c6a7a0204fbb734b15), so that other clients that want `ssb-private` (like patchwork and pay) can install the plugin without having the names conflict.

Sorry for the hassle but we need to break things to make progress.. Currently multiple plugins unbox messages multiple times and it's quite the overhead....

**Comment by joelamouche** [comment]
@arj03 @cryptix Thanks for the help ! Is there any documentation on how to use that plugin? didnt find any on npm nor github...
I installed ssb-private and did the following:

ssbClient(function (err, sbot) {
  if (err)
    throw err

  // sbot is now ready. when done:
  console.log("sbot ready !")
  ssbPrivate.init(sbot,{},function(err,spriv){
	console.log(spriv)
	})
})

And the init fires ssb._flumeUse is not a function (ssb being the instance of ssb-client)

**Comment by cryptix** [comment]
oh, no sorry! you just have to run the following command, so that sbot installs the npm module.:

`sbot plugins.install ssb-private`

Now the sbot instance you get passed from ssbClient will have `sbot.private.publish()` and `.read()`.

**Comment by joelamouche** [comment]
Awesome it works thanks @cryptix :)

**Comment by ZainKhanCC** [comment]
> sbot plugins.install ssb-private



> oh, no sorry! you just have to run the following command, so that sbot installs the npm module.:
> 
> `sbot plugins.install ssb-private`
> 
> Now the sbot instance you get passed from ssbClient will have `sbot.private.publish()` and `.read()`.

Command is not working 
```
/usr/lib/node_modules/ssb-server/node_modules/muxrpcli/index.js:125
      throw err
      ^
TypeError: Cannot set property 'module' of undefined
    at Object.install (/usr/lib/node_modules/ssb-server/node_modules/ssb-plugins/index.js:117:23)
    at Object.hooked (/usr/lib/node_modules/ssb-server/node_modules/hoox/index.js:10:15)
    at Object.localCall (/usr/lib/node_modules/ssb-server/node_modules/muxrpc/local-api.js:31:29)
    at Object.<anonymous> (/usr/lib/node_modules/ssb-server/node_modules/muxrpc/local-api.js:37:22)
    at PacketStreamSubstream.stream.read (/usr/lib/node_modules/ssb-server/node_modules/muxrpc/stream.js:69:23)
    at PacketStream._onstream (/usr/lib/node_modules/ssb-server/node_modules/packet-stream/index.js:228:11)
    at PacketStream.write (/usr/lib/node_modules/ssb-server/node_modules/packet-stream/index.js:135:41)
    at /usr/lib/node_modules/ssb-server/node_modules/muxrpc/pull-weird.js:56:15
    at /usr/lib/node_modules/ssb-server/node_modules/pull-stream/sinks/drain.js:24:37
    at /usr/lib/node_modules/ssb-server/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:17:11

```

**Comment by chongjh** [comment]
@ZainKhanCC I have the same problem. 

As a walkaround, you can `.use(require())` the ssb-private plugin during ssb-server startup.

Example:

```
Server
        .use(require('ssb-master'))
        .use(require('ssb-gossip'))
        .use(require('ssb-replicate'))
        .use(require('ssb-backlinks'))
        .use(require('ssb-private'))
```
