### ISSUE TITLE
Does not work in react-native (because it uses node.js libraries)

### ISSUE THREAD

**Issue by Syed-Kashan-Adil** [ssbc/ssb-client#45]
Unable to resolve module `path` from `/Users/mtahir/Desktop/scuttlebut/node_modules/ssb-client/index.js`: Module `path` does not exist in the Haste module map

**Comment by christianbundy** [comment]
Hey @Syed-Kashan-Adil, sorry to hear you're running into a bug.

Could you describe how you're running this code or give instructions on how to reproduce the problem? I'm not familiar with that error message, although I've found some info here: https://github.com/zetachang/react-native-dotenv/issues/39

**Comment by Syed-Kashan-Adil** [comment]
I am just importing ssb-client and call it. Code gets crash with above mentioned error. 
Code:

const ssbClient  = require("ssb-client");
componentDidMount(){
      ssbClient((err,sbot) => {
      if(err){
          throw(err)
      }
      sbot.publish({
        type  :"post",
        text : "Hello World"
    }, (err,msg) => {
      console.log(msg);
    })

  })
  }

**Comment by christianbundy** [comment]
I see the `componentDidMount()` which makes me think you're using this in a browser. 

cc: @dominictarr, this is meant to work in a browser as well yeah?

**Comment by Syed-Kashan-Adil** [comment]
I am working on react native. Can I run this on node js mobile?

**Comment by christianbundy** [comment]
I believe so, but I'm not sure.

**Comment by Syed-Kashan-Adil** [comment]
Ok. Thank u so much

**Comment by ahdinosaur** [comment]
hm, looks like this would be a problem using `ssb-client` with React Native's JavaScript bundler: [Metro](https://facebook.github.io/metro/)

from my perspective, at the moment the Scuttlebutt stack only explicitly supports the `browserify` JavaScript bundler, but is worth checking out how [Manyverse](https://gitlab.com/staltz/manyverse) got `ssb-client` working.

@Syed-Kashan-Adil: is it possible for you to publish a reproducible example that we could play with, to see the error in detail and explore how we might get things working?

**Comment by ahdinosaur** [comment]
looking at Manyverse, as far as i can tell there the core Scuttlebutt stack runs inside [`nodejs-mobile-react-native`](https://github.com/janeasystems/nodejs-mobile-react-native) as the "backend", where in the "frontend" code re-implements functionality similar to `ssb-client` but without using any modules from the Node.js standard library (like `path`, the module used here).

looks like this could be a possible solution: https://github.com/philikon/ReactNativify:

> The React Native packager has a little known pluggable component called a _transformer_. This is a function that takes a given source file and (typically using Babel) transforms it so that all the funky ES2015 syntax is replaced with stuff that JavaScriptCore can parse. We can supply our own transformer, use a Babel helper called [`babel-plugin-rewrite-require`](https://www.npmjs.com/package/babel-plugin-rewrite-require), and include browserify's reimplementation of node's core libraries to make any piece of code originally written for node.js runnable inside React Native's environment.

/cc @staltz

**Comment by dominictarr** [comment]
yes, browserify put a huge engineering effort in to make node style modules work in the browser. (I did some of that work). browserify works for most ssbc modules, so hopefuly that babel plugin works.

**Comment by staltz** [comment]
Two modules are fundamental to enable using ssb client libraries in React Native:

- https://github.com/ssbc/react-native-ssb-client-keys
- https://github.com/ssbc/react-native-ssb-shims
