### ISSUE TITLE
4.7.7 is available on npm but unavailable on master

### ISSUE THREAD

**Issue by christianbundy** [ssbc/ssb-client#49]
haven't looked into it enough to know what the difference is but I think someone forgot to push to GitHub

**Comment by arj03** [comment]
https://github.com/ssbc/ssb-client/commit/90df79189ce5ff5d7e76a7e8969dca608748fb77?

**Comment by christianbundy** [comment]
Ha! I think I was looking at an old version of the tree on GitHub, my bad. Sorry for the noise and thanks for the quick response.
