### ISSUE TITLE
Can we generate the manifest automaticaly from `api.manifest()`?

### ISSUE THREAD

**Issue by christianbundy** [ssbc/ssb-client#51]
I've always been a bit confused at why this module checks `~/.ssb/manifest.json` instead of calling `manifest()` over muxrpc and returning the results. Is this something that we can safely change, or is there a reason for the manifest to be cached in the filesystem?

cc: @dominictarr @mixmix  @arj03 @staltz

**Comment by dominictarr** [comment]
oh, that's just a historical thing. for the cli it would might be better to just load it over the network.
(although, this would be a breaking change because I'm not sure if other implementations do `manifest()` it's probably time to come up with a standard specification of what apis are provided)
